"""Auto-save: Mon 17 Feb 01:33:07 GMT 2025 (DB migration)

Revision ID: 4b58e208d0d1
Revises: 8f3217136551
Create Date: 2025-02-17 01:33:09.869288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b58e208d0d1'
down_revision: Union[str, None] = '8f3217136551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
