"""Auto-save: Sat  8 Mar 05:35:48 GMT 2025 (DB migration)

Revision ID: 51dbdf76ba1c
Revises: 42a827bab57d
Create Date: 2025-03-08 05:35:50.678474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dbdf76ba1c'
down_revision: Union[str, None] = '42a827bab57d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
