"""Auto-save: Sun 16 Feb 23:46:07 GMT 2025 (DB migration)

Revision ID: caedd262fc56
Revises: 86db7a1d9fe5
Create Date: 2025-02-16 23:46:10.135509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caedd262fc56'
down_revision: Union[str, None] = '86db7a1d9fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
