"""Phew! Got my changes re-applied (DB migration)

Revision ID: e93bed35b9b6
Revises: 0853cdd48927
Create Date: 2025-03-08 06:15:41.527113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93bed35b9b6'
down_revision: Union[str, None] = '0853cdd48927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
